# Generated by Django 4.2.13 on 2024-07-08 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0003_liveclass_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='yoga_class',
        ),
        migrations.AddField(
            model_name='comment',
            name='live_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='yogaapp.liveclass'),
            preserve_default=False,
        ),
    ]
