# Generated by Django 4.2.13 on 2024-07-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0004_remove_comment_updated_at_remove_comment_yoga_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='booked_at',
        ),
    ]
