# Generated by Django 4.2.13 on 2024-07-12 10:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0005_rename_booking_date_booking_booked_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YogaClass',
        ),
        migrations.AddField(
            model_name='liveclass',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
